### ISSUE TITLE
Link to required packages

### ISSUE THREAD

**Issue by lumberjackchef** [MoonMoon1919/Maestro#57]
Suggestion: link to the downloads page for python, boto, pip, etc since they are requirements for running this tool.

**Comment by MoonMoon1919** [comment]
Thanks for the feedback! I'll add this to the readme.

**Comment by lumberjackchef** [comment]
https://github.com/MoonMoon1919/Maestro/pull/60

**Comment by MoonMoon1919** [comment]
Merged. Thanks!
