### ISSUE TITLE
Link to example folder in relevant places

### ISSUE THREAD

**Issue by lumberjackchef** [MoonMoon1919/Maestro#59]
Please link to or reference the example directory in the Notes section of Folder Hierarchy in the README. Doing so will provide much needed clarity to the user on what you're explaining.

**Comment by MoonMoon1919** [comment]
@lumberjackchef https://github.com/MoonMoon1919/Maestro/pull/70

**Comment by lumberjackchef** [comment]
Awesome. Thanks, man!
